# Generated by Django 3.2.3 on 2021-10-16 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teacher_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='reference_number',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
